services:
  frontend:
    image: hsinemt/poulina-sso-frontend:latest
    container_name: poulina-sso-frontend
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
